<?php
// The 28 original hand-authored portfolio pieces, kept exactly as they were
// (same copy as js/omg.js's portfolioItems), with `slug`, `client`, and `year`
// added so each can render its own detail page via project.php and show a
// "Client · Year" line on its card. These stay static/hardcoded — only new
// uploads via admin/upload_portfolio.php go into data/portfolio.json.
function portfolio_static_all(): array {
    return [
        ['id'=>1,'slug'=>'qatar-travel-package','image'=>'images/gallery.jpeg','title'=>'Qatar Travel Package','category'=>'brand','type'=>'Travel & Tourism Flyer','client'=>'Kings Travels','year'=>2026,
            'brief'=>'Kings Travels required a luxury-themed flyer to promote a curated group trip to Qatar.',
            'problem'=>'Travel flyers often look cluttered with too many tiny photos, making the destination feel cheap rather than premium.',
            'challenges'=>"Integrating the iconic Katara Towers architecture with package details while maintaining a clean, aspirational 'sunset' aesthetic.",
            'solution'=>"Used a dominant hero image of Doha's skyline with a torn-paper texture transition to house the text, ensuring the 'Qatar' typography remained the focal point.",
            'outcome'=>'The flyer successfully drove inquiries for the May 2026 window, specifically attracting high-interest travelers via WhatsApp.'],

        ['id'=>2,'slug'=>'valentine-special-promo','image'=>'images/gallery2.jpeg','title'=>'Valentine Special Promo','category'=>'social','type'=>'Seasonal Sales Flyer','client'=>'OMG Graphics','year'=>2025,
            'brief'=>"OMG Graphics needed a self-promotional design to offer a 30% discount on design services during the Valentine's season.",
            'problem'=>"Standard sales flyers can feel transactional; this needed to feel emotional and 'giftable'.",
            'challenges'=>'Working with a monochromatic red palette without making the text unreadable or the icons get lost in the background.',
            'solution'=>"Utilized deep red gradients, 3D floating hearts for depth, and elegant script typography to emphasize the 'Valentine' theme.",
            'outcome'=>'Resulted in a significant uptick in logo and flyer bookings during the February promotion period.'],

        ['id'=>3,'slug'=>'call-to-bar-ceremony','image'=>'images/gallery3.jpeg','title'=>'Call to Bar Ceremony','category'=>'poster','type'=>'Commemorative Invitation','client'=>'Rifkatu Ali Esq.','year'=>2025,
            'brief'=>'A celebratory invitation for Rifkatu Ali Esq. to mark her achievement of being called to the Nigerian Bar.',
            'problem'=>'Legal invitations often look overly formal and dry, lacking a sense of personal celebration.',
            'challenges'=>'Maintaining the dignity of the legal profession (the wig and gown) while creating a festive atmosphere with lighting effects.',
            'solution'=>"A sophisticated dark background with gold 'bokeh' light effects and bold, serif typography to reflect the prestige of the Supreme Court.",
            'outcome'=>"The design served as both a digital invitation and a keepsake for the celebrant's family and colleagues."],

        ['id'=>4,'slug'=>'omg-tech-hub-welcome-to-may','image'=>'images/gallery4.jpeg','title'=>'OMG Tech Hub Welcome to May','category'=>'social','type'=>'Corporate Greeting Flyer','client'=>'OMG Tech Hub','year'=>2026,
            'brief'=>'OMG Tech Hub needed a professional and engaging flyer to welcome the month of May and highlight their diverse digital services.',
            'problem'=>'Monthly greeting flyers often focus solely on the message, missing the opportunity to reinforce brand capabilities and contact information.',
            'challenges'=>"Balancing a professional portrait with a high-tech city background while keeping the service list legible and the 'May' typography prominent.",
            'solution'=>"Utilized a centered subject layout with glowing neon typography for the month, while a clean white footer clearly categorizes five core tech services.",
            'outcome'=>"The flyer successfully updated the brand's social media presence for the new month, encouraging patronage through a direct WhatsApp call-to-action."],

        ['id'=>5,'slug'=>'birthday-flyer','image'=>'images/gallery5.jpeg','title'=>'Birthday Flyer','category'=>'birthday','type'=>'Social Media Birthday Flyer','client'=>'Personal Client (David)','year'=>2025,
            'brief'=>"A multi-photo commemorative flyer for a client named David, celebrating his birthday on April 20th.",
            'problem'=>'The client wanted to showcase multiple outfits and poses without the design feeling like a simple photo collage.',
            'challenges'=>'Creating a cohesive color story between the blue/white jersey and a warm, glowing background.',
            'solution'=>"Used a large 'ghosted' background portrait and a central sharp portrait, surrounded by smaller polaroid-style thumbnails with a warm amber glow.",
            'outcome'=>"The celebrant received high engagement on social media, with the 'reflection' typography at the bottom adding a premium touch."],

        ['id'=>6,'slug'=>'jennifer-avhuri-birthday','image'=>'images/gallery6.jpeg','title'=>'Jennifer Avhuri Birthday','category'=>'birthday','type'=>'Social Media Birthday Flyer','client'=>'Jennifer Avhuri','year'=>2025,
            'brief'=>"A bright, elegant birthday design for Jennifer, emphasizing her personality through descriptive keywords.",
            'problem'=>"The client wanted a 'clean girl' aesthetic that felt airy and luxurious rather than heavy and dark.",
            'challenges'=>'Balancing the gold confetti and silk ribbon elements so they frame the subject rather than distracting from her face.',
            'solution'=>"A minimalist white studio background paired with gold 3D elements and soft typography to highlight her attributes: 'Beautiful, God Fearing, Kind Hearted'.",
            'outcome'=>"A highly shareable Instagram-style flyer that perfectly matched the celebrant's soft-glam aesthetic."],

        ['id'=>7,'slug'=>'anointed-foods-branding','image'=>'images/gallery7.jpeg','title'=>'Anointed Foods Branding','category'=>'brand','type'=>'Business Advertisement Flyer','client'=>'Madam Go Well','year'=>2025,
            'brief'=>'Madam Go Well required a flyer to promote her indoor/outdoor catering services and variety of Nigerian dishes.',
            'problem'=>'Food businesses need to show variety (pastries, rice, swallow) without the flyer looking messy.',
            'challenges'=>'Organizing a long list of food items and contact details into a scannable format.',
            'solution'=>"A circular 'petal' layout for food photography to showcase variety, using a warm 'appetite-stimulating' brown and white color palette.",
            'outcome'=>'The flyer effectively communicated the location (UBTH Back Gate) and drove local foot traffic and catering bookings.'],

        ['id'=>8,'slug'=>'maldives-luxury-waterfall','image'=>'images/gallery8.jpeg','title'=>'Maldives Luxury Waterfall','category'=>'brand','type'=>'Travel & Tourism Flyer','client'=>'Kings Travels','year'=>2026,
            'brief'=>'Kings Travels required an alternative Maldives flyer highlighting the unique architectural and natural waterfall features of premium resorts.',
            'problem'=>'Traditional island flyers can feel repetitive; this design needed to showcase a specific, high-end resort aesthetic to justify a premium price.',
            'challenges'=>"Integrating a vertically complex image of a waterfall and tiered resort structure with a large 'Maldives' heading and detailed tour list.",
            'solution'=>"Applied a textured overlay to the 'Maldives' text to mirror the natural resort vibe, using a torn-paper divider to house package data cleanly.",
            'outcome'=>'The design reinforced the high-value ₦7,800,000 package, specifically targeting travelers looking for unique June 2026 experiences.'],

        ['id'=>9,'slug'=>'skyrise-2nd-anniversary','image'=>'images/gallery9.jpeg','title'=>'Skyrise 2nd Anniversary','category'=>'social','type'=>'Corporate Milestone Flyer','client'=>'SkyRise Realty Ltd','year'=>2025,
            'brief'=>"A celebratory graphic to mark the 2-year anniversary of Skyrise Realty Ltd under the theme 'Audacity of Hope'.",
            'problem'=>'Anniversary posts can often be ignored; this needed to look prestigious and established.',
            'challenges'=>"Working with a dark blue and gold theme to convey 'luxury' while keeping the '2 Years' as the primary visual hook.",
            'solution'=>'Large gold 3D numbering intertwined with a red ribbon and flowing golden light trails against a deep navy background.',
            'outcome'=>'The design reinforced brand trust and longevity, being used as the primary profile display for company stakeholders.'],

        ['id'=>10,'slug'=>'femo-homes-duplex-alert','image'=>'images/gallery10.jpeg','title'=>'Femo Homes Duplex Alert','category'=>'brand','type'=>'Real Estate Listing Flyer','client'=>'Femo Homes and Gardens','year'=>2025,
            'brief'=>'A premium listing flyer for a 4-bedroom semi-detached duplex in Lekki, Lagos, priced at ₦24 Million.',
            'problem'=>"High-value properties need to look expensive. A basic flyer wouldn't justify the ₦24M price tag.",
            'challenges'=>'Showing both the impressive exterior facade and the detailed interior finishes in one square layout.',
            'solution'=>"A hero shot of the 'artistic architecture' at the top, followed by hexagonal interior thumbnails for the living room, bedroom, and kitchen.",
            'outcome'=>"The blue and green color blocking created a 'trustworthy' corporate feel, leading to several physical inspections in the Lekki/Ajah axis."],

        ['id'=>11,'slug'=>'ai-animation-masterclass','image'=>'images/gallery11.jpeg','title'=>'AI Animation Masterclass','category'=>'poster','type'=>'Webinar/Training Flyer','client'=>'Private Client','year'=>2025,
            'brief'=>"A digital creator needed a high-conversion flyer to sell an 'AI Animation' course for ₦3,000.",
            'problem'=>'Tech masterclasses often look intimidating to beginners; the design needed to look accessible yet professional.',
            'challenges'=>'Placing a large amount of course feature text and payment info without the layout feeling cramped.',
            'solution'=>"Used a clean white-to-grey gradient background with red accents to draw attention to the 'Access Fee' and registration call-to-action.",
            'outcome'=>'Clear information hierarchy led to high registration rates, with the price point clearly visible for quick decision-making.'],

        ['id'=>12,'slug'=>'skyrise-february-greeting','image'=>'images/gallery12.jpeg','title'=>'Skyrise February Greeting','category'=>'social','type'=>'Corporate Happy New Month Flyer','client'=>'SkyRise Realty Ltd','year'=>2025,
            'brief'=>'Skyrise Realty needed a branded graphic to maintain social media engagement at the start of February.',
            'problem'=>"Generic 'Happy New Month' posts are often ignored; it needed to reinforce the company's property portfolio.",
            'challenges'=>"Balancing the 'February' greeting with the brand's luxury property aesthetic.",
            'solution'=>'Integrated a high-end modern building render with vibrant red and green typography to evoke a sense of freshness and growth.',
            'outcome'=>"Strengthened brand presence and served as a soft reminder of the client's real estate services to their followers."],

        ['id'=>13,'slug'=>'christian-quote','image'=>'images/gallery13.jpeg','title'=>'Christian Quote','category'=>'social','type'=>'Social Media Quote Card','client'=>'ICCF Missions','year'=>2025,
            'brief'=>'A digital asset for ICCF Missions to share a specific message from Pastor Solomon Folorunsho.',
            'problem'=>"Standard text posts get lost in feeds; the message needed a visual 'anchor'.",
            'challenges'=>'Combining a portrait of the speaker with a large quote block while keeping the text as the primary focus.',
            'solution'=>'Used a clean white speech bubble overlay with bold sans-serif type against a dark, out-of-focus background of the speaker.',
            'outcome'=>"The graphic was widely shared on WhatsApp statuses, effectively spreading the ministry's message beyond the congregation."],

        ['id'=>14,'slug'=>'happy-new-week-skyrise','image'=>'images/gallery14.jpeg','title'=>'Happy New Week - Skyrise','category'=>'social','type'=>'Business Motivational Flyer','client'=>'SkyRise Realty Ltd','year'=>2025,
            'brief'=>'A Monday-morning engagement post for Skyrise Realty to motivate potential investors.',
            'problem'=>'Motivational posts can feel disconnected from the business if not branded correctly.',
            'challenges'=>"Using symbolic imagery (signposts) that aligns with real estate without looking like a stock template.",
            'solution'=>"Designed a custom 3D signpost pointing toward 'Land', 'Property', and 'Investment' to align the greeting with the company's core business.",
            'outcome'=>'High engagement rates on Monday mornings, setting a professional tone for the work week.'],

        ['id'=>15,'slug'=>'apex-academic-services','image'=>'images/gallery15.jpeg','title'=>'Apex Academic Services','category'=>'brand','type'=>'Service Advertisement Flyer','client'=>'Apex Academic Consultancy','year'=>2025,
            'brief'=>'Apex Academic Consultancy needed a flyer to promote their project writing and proofreading services.',
            'problem'=>'Academic services often look boring or overly academic; they needed to look professional yet modern.',
            'challenges'=>'Listing five distinct services while leaving room for a clear contact CTA.',
            'solution'=>'Used 3D academic icons (books, graduation cap, fountain pen) with a sleek black-on-orange info box to grab attention.',
            'outcome'=>'Resulted in a direct increase in WhatsApp inquiries for project editing and business proposal services.'],

        ['id'=>16,'slug'=>'deliverance-from-power-of-darkness','image'=>'images/gallery16.jpeg','title'=>'Deliverance from Power of Darkness','category'=>'poster','type'=>'Church Crusade Flyer','client'=>'ICCF Missions','year'=>2025,
            'brief'=>'International Christian Center for Missions required a spiritual, evocative flyer for their upcoming program in Odighi Village.',
            'problem'=>'Religious posters often use cluttered, low-quality stock images that fail to convey a deep spiritual message.',
            'challenges'=>"Depicting the theme of 'Deliverance' visually without using cliché or frightening imagery.",
            'solution'=>"Used a high-contrast 'reaching hand' metaphor against a textured parchment background to symbolize divine intervention and hope.",
            'outcome'=>'The minimalist approach and clear blue info bar made the event details highly readable for a wide rural audience.'],

        ['id'=>17,'slug'=>'rwanda-urban-exploration','image'=>'images/gallery17.jpeg','title'=>'Rwanda Urban Exploration','category'=>'brand','type'=>'Travel & Tourism Flyer','client'=>'Kings Travels','year'=>2026,
            'brief'=>'A vibrant city-themed flyer for Kings Travels promoting a curated group excursion to Kigali, Rwanda.',
            'problem'=>"Urban travel can sometimes feel less 'aspirational' than beach trips if the design doesn't capture the city's unique architectural beauty.",
            'challenges'=>"Managing the high-energy colors of the Kigali Convention Centre at night without clashing with the sunset sky or branding elements.",
            'solution'=>'Used a dominant skyline hero image and circular insets to showcase local culture and landmarks, tied together with a clean, structured footer.',
            'outcome'=>'This flyer attracted interest for the June 10th–14th window, positioning Rwanda as a premier African destination for high-interest travelers.'],

        ['id'=>18,'slug'=>'sebfon-academy-class-banner','image'=>'images/gallery18.jpeg','title'=>'Sebfon Academy Class banner','category'=>'poster','type'=>'School Group Photo Flyer','client'=>'Sebfon Academy','year'=>2025,
            'brief'=>'A secondary graduation graphic for Sebfon Academy, focusing on group class photos and staff.',
            'problem'=>'Group photos have different aspect ratios and lighting; they needed to be unified.',
            'challenges'=>"Arranging 14 different group photos ranging from Staff to JSS 3 without losing the celebratory feel.",
            'solution'=>"A balanced peripheral layout where the smallest classes and staff frame the central 'Happy Graduation' logo.",
            'outcome'=>"Used as a featured post on the school's website for a period of time to showcase their student body and academic staff."],

        ['id'=>19,'slug'=>'nerrgs-boutique-sales','image'=>'images/gallery19.jpeg','title'=>"Nerrg's Boutique Sales",'category'=>'brand','type'=>'Retail Fashion Flyer','client'=>"Nerrg's Boutique",'year'=>2025,
            'brief'=>"A luxury-style flyer for Nerrg's Boutique to showcase their collection of designer wears and accessories.",
            'problem'=>'Showing clothes, watches, shoes, and perfume all at once can look like a catalog rather than an ad.',
            'challenges'=>"Creating a 'high-fashion' feel using flat product photography.",
            'solution'=>'A deep maroon and gold color scheme with a grid of lifestyle product shots flanking a central hero image of a premium tuxedo.',
            'outcome'=>"Successfully positioned the boutique as a 'one-stop shop' for luxury event outfits, specifically for the wedding season."],

        ['id'=>20,'slug'=>'maldives-overwater-villa','image'=>'images/gallery20.jpeg','title'=>'Maldives Overwater Villa','category'=>'brand','type'=>'Travel & Tourism Flyer','client'=>'Kings Travels','year'=>2026,
            'brief'=>'A sunset-themed flyer for Kings Travels showcasing the iconic overwater villa experience in the Maldives.',
            'problem'=>'Standard villa photos can lose their impact if the layout is too busy with text boxes that obscure the scenic horizon.',
            'challenges'=>'Placing a large date banner and package details over a detailed drone shot of the villa lineup while maintaining a luxury feel.',
            'solution'=>"Leveraged a sunset hero image as the primary background, using a 'torn paper' texture at the bottom to provide a neutral space for the itinerary.",
            'outcome'=>'The flyer effectively communicated the romantic appeal of the June 2026 window, driving direct inquiries for the ₦7,800,000 per person package.'],

        ['id'=>21,'slug'=>'christian-discipleship-centre-summit','image'=>'images/gallery21.jpeg','title'=>'Christian Discipleship Centre Summit','category'=>'poster','type'=>'Religious Event Flyer','client'=>'Christian Discipleship Centre','year'=>2025,
            'brief'=>"The Christian Discipleship Centre required a clean, heavenly-themed flyer for their 2025 Summit titled 'IN HIM'.",
            'problem'=>'Church flyers often use dark or cluttered imagery that can feel heavy; the client wanted something that felt light and airy.',
            'challenges'=>'Working with a very bright background while ensuring white text remains readable and professional.',
            'solution'=>"Used a sky-blue cloud background with heavy black outlines on the main title and distinct stroke-bordered boxes for the venue and date.",
            'outcome'=>"The high-contrast 'IN HIM' centerpiece effectively drew attention to the theme, making it easily recognizable on digital notice boards."],

        ['id'=>22,'slug'=>'sebfon-academy-cultural-celebration','image'=>'images/gallery22.jpeg','title'=>'Sebfon Academy Cultural Celebration','category'=>'poster','type'=>'Cultural Event Poster','client'=>'Sebfon Academy','year'=>2025,
            'brief'=>"A digital portrait-centric version of the Cultural Day event flyer, focusing on the students' traditional attire.",
            'problem'=>"The client wanted a version that felt more 'human' and focused on the children participating.",
            'challenges'=>'Removing backgrounds from diverse group photos and blending them into a cohesive green and white aesthetic.',
            'solution'=>"Centered three high-energy student portraits in traditional gear with a vibrant green 'forest' glow to represent the Nigerian colors.",
            'outcome'=>'This version became the primary poster for physical printouts around the school premises and digital dissemination due to its high visual energy.'],

        ['id'=>23,'slug'=>'sebfon-academy-cultural-day-banner','image'=>'images/gallery23.jpeg','title'=>'Sebfon Academy Cultural Day banner','category'=>'poster','type'=>'Educational Event Invitation','client'=>'Sebfon Canadian Academy','year'=>2025,
            'brief'=>'Sebfon Canadian Academy needed a vibrant, festive invitation for their first-ever Cultural Day event.',
            'problem'=>"The flyer needed to represent 'culture' broadly without favoring one specific tribe, while listing many activities.",
            'challenges'=>'Fitting a long list of features (talent hunts, drama, parade) alongside diverse cultural imagery.',
            'solution'=>'Used a clean white center for the text to ensure readability, framed by traditional drums and colorful patterns at the top and bottom.',
            'outcome'=>'The design successfully communicated the variety of the event, leading to a massive turnout of parents and students in traditional attire.'],

        ['id'=>24,'slug'=>'ziggy-world-business-services','image'=>'images/gallery24.jpeg','title'=>'Ziggy World Business Services','category'=>'poster','type'=>'Business Portfolio Flyer','client'=>'Ziggy World','year'=>2025,
            'brief'=>'Ziggy World needed a flyer to advertise their diverse range of services, from medical equipment to printing.',
            'problem'=>'The business handles very different niches (books vs. medical scrubs); the design needed to look unified.',
            'challenges'=>"Combining imagery of medical scrubs and school books in a way that doesn't look disorganized.",
            'solution'=>'Used a deep blue professional background with color-coded info blocks and high-quality 3D renders of the products.',
            'outcome'=>'The flyer clearly categorized the business offerings, helping customers understand that they could get both medical supplies and printing done at one location.'],

        ['id'=>25,'slug'=>'omg-graphics-hire-flyer','image'=>'images/gallery25.jpeg','title'=>'OMG Graphics Hire Flyer','category'=>'brand','type'=>'Agency Service Advertisement','client'=>'OMG Graphics','year'=>2026,
            'brief'=>"OMG Graphics needed a 'vibe-check' flyer to attract new clients by showcasing their creative tools and service list.",
            'problem'=>"Designers' own flyers are often too experimental, making them hard for non-designers to read.",
            'challenges'=>"Visualizing the 'creative process' while listing over eight specific design services.",
            'solution'=>'Used a dark tech-themed top half with software icons (Ps, Ai) and a clean white bottom half for the service list to ensure high scannability.',
            'outcome'=>"The 'Do You Need A Graphic Designer?' hook led to a 25% increase in cold inquiries from local small businesses."],

        ['id'=>26,'slug'=>'promise-land-estate','image'=>'images/gallery26.jpeg','title'=>'Promise Land Estate','category'=>'brand','type'=>'Real Estate Marketing Flyer','client'=>'SkyRise Realty Ltd','year'=>2025,
            'brief'=>"Skyrise Realty needed to promote land plots in Adesagbon Community with a specific 'Free Trip of Sand' incentive.",
            'problem'=>'Land sales in Nigeria are competitive; the offer (price and bonuses) needed to stand out immediately.',
            'challenges'=>"Blending a blue-sky outdoor aesthetic with the corporate branding of the realty company.",
            'solution'=>"High-visibility red and black text for the 'Promise Land' title and a dedicated bubble for the price list ($1.2M - $2M) for instant clarity.",
            'outcome'=>"The 'Free Trip of Sand' highlight became a major talking point for leads, increasing conversion rates for the Benin-Auchi express road plots."],

        ['id'=>27,'slug'=>'seychelles-tropical-gateway','image'=>'images/gallery27.jpeg','title'=>'Seychelles Tropical Gateway','category'=>'brand','type'=>'Travel & Tourism Flyer','client'=>'Kings Travels','year'=>2026,
            'brief'=>'Kings Travels commissioned a warm, tropical flyer to promote a multi-day group trip to the Seychelles islands.',
            'problem'=>'Multiple package inclusions can make a flyer feel like a grocery list rather than an invitation to a luxury vacation.',
            'challenges'=>'Combining a sunset resort view with cultural tour highlights while keeping the ₦2,600,000 pricing clear and attractive.',
            'solution'=>'Framed the main resort view as the emotional hook, using circular thumbnails to visually represent the city tours and temple visits mentioned in the text.',
            'outcome'=>'The flyer saw high engagement for the May 2026 travel window, successfully converting interested travelers via the integrated WhatsApp contact.'],

        ['id'=>28,'slug'=>'dreamland-gardens-promo','image'=>'images/gallery28.jpeg','title'=>'Dreamland Gardens Promo','category'=>'poster','type'=>'Sales Incentive Flyer','client'=>'SkyRise Realty Ltd','year'=>2025,
            'brief'=>'A high-impact promotional flyer for Skyrise Realty to push their ₦500k deposit plan for land.',
            'problem'=>"The low deposit price needed to be the hero of the design to drive 'impulse' real estate inquiries.",
            'challenges'=>"Making the price tag look 'valuable'—not cheap—while showcasing the potential of the land development.",
            'solution'=>"Used a giant golden 'banner' tag to house the ₦500k figure, placing it centrally over a high-end architectural render.",
            'outcome'=>"The '₦500k Deposit' became the most recognized part of the campaign, leading to high conversion for the Iguoviobo Community plots."],
    ];
}
